name: Tests

# Controls when the action will run.
on:
  push:
    branches: ["main", "a3"]
  pull_request:
    branches: ["*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 100
    strategy:
      matrix:
        node-version: [20]
        mongodb-version: [7.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - run: npm test --verbose
        env:
          CI: true
        timeout-minutes: 45

      - run: npm test
        if: always()
        env:
          CI: true
        timeout-minutes: 45

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.node-version }}-${{ matrix.mongodb-version }}
          path: |
            ./.nyc_output/
            ./coverage/
          retention-days: 5